version: "3.9"
services:
  echo:
    build: EchoService
    image: mniak/echo
    ports:
      - "5000:80"
  proxy:
    build: AuthProxy
    image: mniak/sidecar_proxy_demo
    environment:
      - "Proxy__Upstream=http://echo:80"
    ports:
      - "5050:8080"
